Rails.application.routes.draw do
  # Session and password routes
  resource :session
  resources :passwords, param: :token

  # Health check route for uptime monitoring
  get "up" => "rails/health#show", as: :rails_health_check

  # Root route (products index)
  root "products#index"

  # Standard RESTful routes for products (this generates all necessary routes automatically)
  resources :products do
    # Nested resource for subscribers and unsubscribe
    resources :subscribers, only: [:create]
    resource :unsubscribe, only: [:show]
  end

  # You can also define the "new" action directly if needed:
  # get "/products/new", to: "products#new"

  # If you need to define some non-RESTful routes for specific actions, you can do so here.
  # However, avoid duplicating the standard RESTful routes generated by `resources :products`.

  # Example for the health check route (already defined above)
  # get "/up", to: "rails/health#show"
end
